####################################################################
runInJenkins = Y
finalLoopValue=1
bankHoliday=n
headless=false

##########################FOR DATABASE##################################

jdbc.password=pXY6AFmos2EgJls4IF/Udg==
jdbc.username=admin
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://192.168.85.142:3307/nonsbi_db?connectTimeout=5000
######################FOR OTP#######################################
otp.jdbc.driver=com.mysql.jdbc.Driver
otp.jdbc.url=jdbc:mysql://114.79.172.202:3306/test?connectTimeout=5000&useSSL=false
otp.jdbc.username=root
otp.jdbc.password=Apmosys@123
#otp.makerMobileNo=8591462635
#otp.makerMobileNo=8828417633
#otp.checkerMobileNo=916764094
Corporate_OTP=8591462618
Authoriser_OTP=9321975713
Maker_OTP=8591462615
sbi_otp=8591462618
SBI=9372669410
secondValue=10
SAHARA_PORTAL=9082248910

location=navi mumbai

monitoringBusinessHour=n
monitoringDataSheetPath=
businessHourRunStatus=
businessHourFunctions=
########################## for error alrt ################################
mailAlert=N
alertmailTo=
alertmailCC=

######################FOR MAIL ALERT################################
host=apmosys.icewarpcloud.in
port=587
mailFrom=alerts@apmosys.com
authId=
password=
subject= 
message= 
mailTo=
mailCc=
errorMsg=
extraMsg=
####################################################################

#businessHourRunStatus=1
#businessHourFunctions=SbI_Add_Manage_Beneficiary_BusinessHour

onMarket=n
scType=n

URL=https://www.smsgateway.center/SMSApi/rest/send?
userId=bibhu
SMSpassword=ApMoSys@0210
senderId=APMSYS
msg=Level test Error on test Page test at test on test for test
mobile=8338065853

#for monitoring business hour 
monitoringBusinessHour=n
monitoringDataSheetPath=n

#/home/apmosys/bkp/eclipse-workspace/4Oct2022/SBI_NONSBI_HAR/HARFolder/
#HAR PROPERTIES
harPath = /home/apmosys/bkp/eclipse-workspace/4Oct2022/SBI_NONSBI_HAR/HARFolder/
har_generation = Y
jdbc.password=T3BlcmF0aW9uQDEyMw==
jdbc.username=SynMonitoring
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://192.168.1.228:3306/nonsbi_final?connectTimeout=5000
